# -*- coding: utf-8 -*-
import os, csv, re, time, requests, json
import numpy as np
from pathlib import Path
from dotenv import load_dotenv

from pythainlp.tokenize import word_tokenize
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer, CrossEncoder
from langchain_text_splitters import RecursiveCharacterTextSplitter
from tqdm import tqdm

load_dotenv()
THAILLM_API_KEY = os.environ.get("THAILLM_API_KEY", "1p1dC5cHTY9G4myMrb48gixAdDcFA55L")

# === CONFIGURATION ===
N_QUESTIONS = 100
DATA_DIR = "./data"
KB_DIR = f"{DATA_DIR}/knowledge_base"
USE_CONTEXTUAL_ENRICHMENT = False # Disabled for speed

MODEL_ENDPOINT = "pathumma" 
MODEL_PAYLOAD_NAME = "Pathumma-ThaiLLM-qwen3-8b-think-3.0.0"

# === CHECKPOINT FILE ===
BACKUP_SUBMISSION = "backup_submission_pathumma.csv"

# === 0. LLM UTILS ===
def ask_llm(messages, max_retries=5, temperature=0.3):
    url = f"http://thaillm.or.th/api/{MODEL_ENDPOINT}/v1/chat/completions"
    headers = {"Content-Type": "application/json", "apikey": THAILLM_API_KEY}
    
    payload = {
        "model": MODEL_PAYLOAD_NAME,
        "messages": messages,
        "max_tokens": 1500,
        "temperature": temperature,
    }
    
    for attempt in range(max_retries):
        try:
            resp = requests.post(url, headers=headers, json=payload, timeout=90)
            if resp.status_code == 429:
                time.sleep(min(2 ** attempt, 10))
                continue
                
            # Dynamic URL fallback in case ThaiLLM uses literal model string in URL
            if resp.status_code in [400, 404]:
                print(f"Fallback URL attempt for {MODEL_PAYLOAD_NAME}...")
                payload["model"] = "/model"
                url = f"http://thaillm.or.th/api/{MODEL_PAYLOAD_NAME}/v1/chat/completions"
                resp = requests.post(url, headers=headers, json=payload, timeout=90)
                
            resp.raise_for_status()
            return resp.json()["choices"][0]["message"]["content"].strip()
        except requests.exceptions.RequestException as e:
            print(f"\n[API WARNING] Attempt {attempt+1} Failed: {e}")
            time.sleep(min(2 ** attempt, 10))
            
    print("\n[API ERROR] All 5 retries failed! The server might be down (e.g., 502 Bad Gateway). Returning empty string.")
    return ""

def parse_answer(text):
    if not text: return 9
    
    # Clean out the <think> reasoning block generated by Pathumma-think
    clean = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL).strip()
    
    m = re.search(r"ANSWER:\s*(\d+)", clean, re.IGNORECASE)
    if m: return int(m.group(1))
    
    # Extreme parsing fallback if it still missed
    for d in re.findall(r"\b(\d{1,2})\b", clean):
        if 1 <= int(d) <= 10: return int(d)
        
    return 9 # Fallback if not sure
    
# Table Unrolling
def unroll_markdown_tables(text):
    lines = text.split('\n')
    unrolled_lines = []
    in_table = False
    headers = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('|') and stripped.endswith('|'):
            cells = [c.strip() for c in stripped.strip('|').split('|')]
            if all(set(c) <= set('- :') for c in cells):
                continue
            if not in_table:
                in_table = True
                headers = cells
            else:
                row_info = ", ".join(f"{h}: {c}" for h, c in zip(headers, cells) if h and c)
                unrolled_lines.append(f"• ข้อมูลตาราง: {row_info}")
        else:
            in_table = False
            unrolled_lines.append(line)
    return '\n'.join(unrolled_lines)


# === 1. DATA PREPARATION (PHASE 1) ===
def get_or_build_chunks():
    kb_dir = Path(KB_DIR)
    documents = []
    if kb_dir.exists():
        for fp in sorted(kb_dir.rglob("*.md")):
            raw_text = fp.read_text(encoding="utf-8")
            unrolled_text = unroll_markdown_tables(raw_text)
            documents.append({
                "path": str(fp.relative_to(kb_dir)), 
                "text": unrolled_text
            })

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=50)
    
    chunks = []
    for doc in documents:
        for text in text_splitter.split_text(doc["text"]):
            chunks.append({"text": text, "source": doc["path"]})
            
    print(f"Found {len(documents)} documents, split into {len(chunks)} chunks.")
    return chunks

# === 2. INDEXING ===
chunks = get_or_build_chunks()

print("\nLoading BAAI/bge-m3 for Vector Search...")
embed_model = SentenceTransformer("BAAI/bge-m3")
chunk_texts = [c["text"] for c in chunks]

EMBEDDINGS_CACHE = "embeddings_cache.npy"
if os.path.exists(EMBEDDINGS_CACHE):
    chunk_embeddings = np.load(EMBEDDINGS_CACHE)
else:
    chunk_embeddings = embed_model.encode(chunk_texts, batch_size=32, show_progress_bar=True, normalize_embeddings=True)
    np.save(EMBEDDINGS_CACHE, chunk_embeddings)

print("\nBuilding BM25 Index for Keyword Search...")
tokenized_chunks = [word_tokenize(c["text"], engine="newmm") for c in chunks]
bm25 = BM25Okapi(tokenized_chunks)

print("\nLoading Cross-Encoder for Reranking (BAAI) - Highly Recommended for Accuracy...")
cross_encoder = CrossEncoder("BAAI/bge-reranker-v2-m3", max_length=512)


# === 3. INFERENCE PIPELINE ===
def retrieve_top_k(query, fetch_k=30):
    q_emb = embed_model.encode([query], normalize_embeddings=True)
    dense_scores = np.dot(chunk_embeddings, q_emb.T).flatten()
    dense_idx = np.argsort(dense_scores)[::-1][:fetch_k]
    
    tokens = word_tokenize(query, engine="newmm")
    bm25_scores = bm25.get_scores(tokens)
    bm25_idx = np.argsort(bm25_scores)[::-1][:fetch_k]
    
    rrf_k = 60
    rrf_scores = {}
    for rank, idx in enumerate(dense_idx, 1):
        rrf_scores[idx] = rrf_scores.get(idx, 0) + 1.0 / (rrf_k + rank)
    for rank, idx in enumerate(bm25_idx, 1):
        rrf_scores[idx] = rrf_scores.get(idx, 0) + 1.0 / (rrf_k + rank)
        
    merged_idx = sorted(rrf_scores.keys(), key=lambda x: rrf_scores[x], reverse=True)[:fetch_k]
    return merged_idx

def rerank_to_top_7(query, candidate_indices, top_k=7):
    # Using top_k=7 gives the LLM slightly more context to evaluate correctly.
    pairs = [[query, chunks[idx]["text"]] for idx in candidate_indices]
    cross_scores = cross_encoder.predict(pairs)
    top_indices = np.argsort(cross_scores)[::-1][:top_k]
    return [candidate_indices[i] for i in top_indices]


# === 4. EXECUTION LOOP ===
questions = []
try:
    with open(f"{DATA_DIR}/questions.csv", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            choices = {str(i): row[f"choice_{i}"] for i in range(1, 11)}
            questions.append({"id": int(row["id"]), "question": row["question"], "choices": choices})
except FileNotFoundError:
    print("Warning: data/questions.csv not found.")

sys_prompt = """คุณคือ AI ผู้ช่วยร้านฟ้าใหม่ หน้าที่ของคุณคือตอบคำถามลูกค้าอย่างรอบคอบและถูกต้องที่สุด
จงตอบคำถามโดยอ้างอิงจาก [ข้อมูลอ้างอิง] ต่อไปนี้เป็นหลัก ห้ามแต่งเนื้อหาเพิ่มเติมเอง

[กติกาการตัดสินใจ]
- ให้สรุปกระบวนการคิดอยู่ในแท็ก <think> และเขียนคำตอบตัดสินใจสุดท้าย อยู่นอกแท็ก
- หากมีระบุในเนื้อหาชัดเจน ให้ตอบข้อ 1-8 ที่ถูกต้องเพียง 1 ตัวเลือก
- แต่ถ้าข้อมูลไม่เกี่ยวข้องกันเลยจริงๆ หรือหาคำตอบไม่ได้จากเอกสาร ให้ตอบ 9 หรือ 10 เท่านั้น"""

results = []
done_qids = set()
if os.path.exists(BACKUP_SUBMISSION):
    with open(BACKUP_SUBMISSION, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader, None)
        for row in reader:
            if row:
                qid_val = int(row[0])
                results.append([qid_val, int(row[1])])
                done_qids.add(qid_val)
else:
    with open(BACKUP_SUBMISSION, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "answer"])

print(f"Running PATHUMMA pipeline on {min(N_QUESTIONS, len(questions))} questions...")
for q in questions[:N_QUESTIONS]:
    q_id = q["id"]
    original_q = q["question"]
    
    if q_id in done_qids:
        continue
    
    # Retrieval (Hybrid -> Reranking)
    top30_idx = retrieve_top_k(original_q, fetch_k=30)
    final_top7_idx = rerank_to_top_7(original_q, top30_idx, top_k=7)
    retrieved_chunks = [chunks[i] for i in final_top7_idx]
    
    context_text = "\n\n".join(f"--- ข้อมูล {i+1} ---\n{c['text']}" for i, c in enumerate(retrieved_chunks))
    choices_text = "\n".join(f"{k}. {v}" for k, v in q["choices"].items())
    
    final_prompt = (
        f"[ข้อมูลอ้างอิง]\n{context_text}\n\n"
        f"[คำถามจากลูกค้า]\n{original_q}\n\n"
        f"[ตัวเลือก]\n{choices_text}\n\n"
        f"จงวิเคราะห์สถานการณ์ เขียนกระบวนการคิดในแท็ก <think> \n"
        f"และพิมพ์คำตอบสุดท้ายในรูปแบบ ANSWER: X (X คือเลขช้อยส์)"
    )
    
    raw = ask_llm([
        {"role": "system", "content": sys_prompt},
        {"role": "user", "content": final_prompt}
    ], temperature=0.3)
    
    ans = parse_answer(raw)
    results.append([q_id, ans])
    
    has_think = "<think>" in raw
    if not raw:
        print(f"  Q{q_id:>3}: Ans=9 ❌ (API Server Offline/Failed)")
    else:
        print(f"  Q{q_id:>3}: Ans={ans} | Used <think>: {has_think} | Token Gen: {len(raw)}")
    
    with open(BACKUP_SUBMISSION, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([q_id, ans])

with open("pathumma_submission.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["id", "answer"])
    writer.writerows(results)

print("PATHUMMA pipeline complete! Saved to pathumma_submission.csv")
